// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8gdk5axOTvZKJmkW-4KDkqNQNnMjIxiA',
    appId: '1:992462879712:web:0e50f83b123c839b6d4985',
    messagingSenderId: '992462879712',
    projectId: 'certychain-4ab06',
    authDomain: 'certychain-4ab06.firebaseapp.com',
    databaseURL: 'https://certychain-4ab06-default-rtdb.firebaseio.com',
    storageBucket: 'certychain-4ab06.appspot.com',
    measurementId: 'G-4E03DCX7SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ-JZF3mYBlIxHzNGGWWx0SYvYvfpHpbY',
    appId: '1:992462879712:android:64017ec64ffe060f6d4985',
    messagingSenderId: '992462879712',
    projectId: 'certychain-4ab06',
    databaseURL: 'https://certychain-4ab06-default-rtdb.firebaseio.com',
    storageBucket: 'certychain-4ab06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFQu-zGjCSlvB4xImjmhGb7fTOsZ9ah6I',
    appId: '1:992462879712:ios:e5bac4b7dafc33b26d4985',
    messagingSenderId: '992462879712',
    projectId: 'certychain-4ab06',
    databaseURL: 'https://certychain-4ab06-default-rtdb.firebaseio.com',
    storageBucket: 'certychain-4ab06.appspot.com',
    iosClientId: '992462879712-cvj5b6q3ge0tem8o7q558rsp3qncnc42.apps.googleusercontent.com',
    iosBundleId: 'com.example.certyChainNrb',
  );
}
